version: '3.7'

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8085:8080

volumes:
  postgres:
